#!/bin/bash
# Ensure Jupyter runtime/data dirs are on local filesystem
# (workaround for slow WebDAV/NFS mounts from EGI owncloud sidecars)
export JUPYTER_RUNTIME_DIR=/tmp/jupyter-runtime
export JUPYTER_DATA_DIR=/tmp/jupyter-data
mkdir -p "$JUPYTER_RUNTIME_DIR" "$JUPYTER_DATA_DIR"

exec "$@"
